### ISSUE TITLE
Followed Tutorial 3 but failed 2 test cases

### ISSUE THREAD

**Issue by Impala36** [nus-tic4002-AY2021S2/forum#11]
Hi guys,

I have added the Remark command, field and tests [#6](https://github.com/TIC4002-F18-1/tp2/pull/6) as followed in [Tutorial 3 - Adding a new Command](https://nus-tic4002-ay2021s2.github.io/tp2/tutorials/AddRemark.html) but failed 2 tests out of 255 when running gradle build.
The remarks work fine in the program without any errors.
I would really appreciate your help.
You can view the test results here: [test.zip](https://github.com/nus-tic4002-AY2021S2/forum/files/5943035/test.zip)

![image](https://user-images.githubusercontent.com/44335297/107208002-f458b100-6a3b-11eb-8a8a-872818ec18ed.png)

**Comment by damithc** [comment]
@Impala36 Try this:
Identify one of the failed tests.
Run that test using intellij
Examine the result i.e. expected, actual
The above should point you towards a solution
If not, can post here the specific test and the expected/actual or the stack trace.

**Comment by Impala36** [comment]
Thanks Prof. I have tried, but I still don't understand why it works that way. The remark field should be fine being blank, but is considered as missing. The full stack trace is found in [test.zip](https://github.com/nus-tic4002-AY2021S2/forum/files/5943035/test.zip).
# JsonSerializableAddressBookTest
## toModelType_duplicatePersons_throwsIllegalValueException()
org.opentest4j.AssertionFailedError: expected: <Persons list contains duplicate person(s).> but was: <Person's Remark field is missing!>
	at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
	at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:195)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:184)
	at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:179)
	at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
	at seedu.address.testutil.Assert.assertThrows(Assert.java:32)
	at seedu.address.storage.JsonSerializableAddressBookTest.toModelType_duplicatePersons_throwsIllegalValueException(JsonSerializableAddressBookTest.java:43)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	...
	
## toModelType_typicalPersonsFile_success()
seedu.address.commons.exceptions.IllegalValueException: Person's Remark field is missing!
	at seedu.address.storage.JsonAdaptedPerson.toModelType(JsonAdaptedPerson.java:111)
	at seedu.address.storage.JsonSerializableAddressBook.toModelType(JsonSerializableAddressBook.java:51)
	at seedu.address.storage.JsonSerializableAddressBookTest.toModelType_typicalPersonsFile_success(JsonSerializableAddressBookTest.java:27)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	...

**Comment by damithc** [comment]
Seems like the storage code (specifically, the part that serializes/desterilizes objects to/from json format) hasn't been updated to cater for the new field you added.

This old issue https://github.com/nus-cs2103-AY2021S1/forum/issues/282 seems somewhat related (might give you some ideas if not the solution)

Post again if the above doesn't help you locate the problem, you can compare with [this PR](https://github.com/AY2021S1-CS2103T-W16-3/tp/pull/41/files) (which seems to be passing the tests) to see where you differ.

**Comment by Impala36** [comment]
Yes, you're right. I forgot to update the remark field for Add remark section to duplicatePersonAddressBook.json and typicalPersonsAddressBook.json in the test data JsonSerializableAddressBookTest folder.
The [PR](https://github.com/AY2021S1-CS2103T-W16-3/tp/pull/41/files) you posted does have those files updated.
Many thanks, Prof!
